# Generated by Django 4.2.11 on 2025-11-20 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lostitem',
            name='claimed',
            field=models.BooleanField(default=False, help_text='Marked true when verified claimed by rightful owner'),
        ),
    ]
