# Generated by Django 4.2.11 on 2025-11-20 21:30

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_lostitem_claimed'),
    ]

    operations = [
        migrations.AddField(
            model_name='lostitem',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='Public unique identifier', unique=True),
        ),
    ]
