# Generated by Django 4.2.11 on 2025-11-23 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0003_lostitem_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lostitem',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='item_images/'),
        ),
    ]
