# Generated by Django 4.2.11 on 2025-11-23 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0009_message_attachment'),
        ('items', '0010_add_found_field'),
    ]

    operations = [
    ]
